// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_UWPWebView2_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::UWPWebView2::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::UWPWebView2
{
    MainPage::MainPage() :
        MainPage(make<UWPWebView2::implementation::MainPage>())
    {
    }
}
