// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_UWPWebView2_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::UWPWebView2::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::UWPWebView2
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<UWPWebView2::implementation::XamlMetaDataProvider>())
    {
    }
}
