// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_UWPWebView2_0_H
#define WINRT_UWPWebView2_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::UWPWebView2
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::UWPWebView2::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::UWPWebView2::MainPage>{ using type = class_category; };
    template <> struct category<winrt::UWPWebView2::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::UWPWebView2::MainPage> = L"UWPWebView2.MainPage";
    template <> inline constexpr auto& name_v<winrt::UWPWebView2::XamlMetaDataProvider> = L"UWPWebView2.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::UWPWebView2::IMainPage> = L"UWPWebView2.IMainPage";
    template <> inline constexpr guid guid_v<winrt::UWPWebView2::IMainPage>{ 0x530681C2,0x0FA4,0x50C1,{ 0xA0,0x25,0x19,0x7B,0x29,0x16,0xEC,0x7E } }; // 530681C2-0FA4-50C1-A025-197B2916EC7E
    template <> struct default_interface<winrt::UWPWebView2::MainPage>{ using type = winrt::UWPWebView2::IMainPage; };
    template <> struct default_interface<winrt::UWPWebView2::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::UWPWebView2::IMainPage>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_UWPWebView2_IMainPage
    {
    };
    template <> struct consume<winrt::UWPWebView2::IMainPage>
    {
        template <typename D> using type = consume_UWPWebView2_IMainPage<D>;
    };
}
#endif
